title: kw7oe
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://old.kaiwern.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: kw7oe
github_username:  kw7oe
# disqus:
#   shortname: kw7oe-github-io


plugins:
  - jekyll-archives
  - jekyll-feed
  - jekyll-paginate
  - jekyll-compose

# jekyll_compose:
#   auto_open: true

# Build settings
markdown: kramdown

# Pagination
paginate: 5
paginate_path: "/blog/page-:num"

# Archives
jekyll-archives:
  enabled:
    - categories
  layouts:
    category: category-archive
  permalinks:
    category: '/categories/:name/'

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
